# Generated by Django 6.0.1 on 2026-06-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(max_length=10),
        ),
    ]
